travis:
  secure:
    BINSTAR_TOKEN: ODeL2bmMvGXwajT97wSpJtgQ+AwpyBrgk4A44oyEAvy+URO690+hQ24hA/XR2nUbcavWaofvjFRJGN/lS8Elz/CCu/GXSYjUdmwizKeS+cHxmo/qRXRtUqodLCpf0W5mMVp1/hJYyi8jxqPTlHjgC+HAPN6ouqSduI7+aoChEGiFxdFiXTm+eyaqqv7+zdR3nfxoHGyE2+/BJ/xgeDR9N3h/L1G3QnW3NSLjvwUcZ8w8xyk14uIEwdq/U6YaepXlei7fdBUAXvo4pHNaO8xNY7f2vriGjfL+Fa0JsBzrAyDuRWiFcW1zfP/7wX2egDh/aA58wIFvUhZ0VLha1scTHYKDn57ZdHPR50sgUCf7LA0zPhnV3VulmJexhp3RKyz8BI0QTXQu4MfBmnZKwMxDK5IMRfvT1uvE7Rn/KM/irHG4s2M+64mm53uK9y2C9+F/8UT9jEjCpbbuMZPmYl+QeqRrmq15OPba5gTKR/R6/etIpZZA6Zy7amYQrjvJ5nB7QjbMcxSD1p2OOJ9nTM3EZN75DmHik11LSZmzqUYfkbNNfUGYZDt2UXfy2jcYYCkBt5tju1mOuW2PDKdoQLjDWYnw/pmieEEbJhJFDZrDyfA+n1TmyRzcRlF1VYbzBzKbB3Dtt5s+sIg/I7e9JL4gIdkWnd8J4gFcGmqE8zomgoc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
