travis:
  secure:
    BINSTAR_TOKEN: LWqXV2K6DN3kIiVMEXbhUDL3BEPHpK5BgykyYJDa1Fkg82ZLCa6wdOpUZ2fTRwXmUUs5EzRz/AmqXKxkL24G5qNHLNpmEskyl9X62l0Ku/VlY7vUUbMTxjR/MX4zpPMS0qk/wMv7xyRv5VSqZbFi0RIE9KnywuJiifB9xbBAtTIAXT88Y/awYMztL7Q7cLBUOCe7MDB4GiGVvvRr2fJWduhO9Trlx5LXoKaiVUQ70MeYepfKLjz+deJeFI39xVTmVJzR+tmgadgRilRk9zc1MI2rrJjg5VxKCluLcEXX4zPnPMVfoG7w6rwIavt1uYoMJ2lp8eKklAgrofFPPLagaylebZKy9wzhF6kbtrjdC3Zq5yl5RGmHfZuoyTyb4dbRT10ZEEN9H7k1HvcVp7YOwTXIKuBqf2iiJ5cbbjwNkCDvPPbyw9dKHHGc+rnYjReSFBUDTnZ/KxWD8buiEBDlFt0fVcUopHAL5L55hyIc9cpNj21s7qK12TuFoXIzG02d4zd99Bb7JwglHa9fmHv/CNv8UBXpEnZH6/In2N1Z0wBPk52QSGpJQ4FVpQYJElgQEAXux9G+OQP53P/9nABF513ROaWfegJ4CLAxm9iRm5N2ZHmMmd72D158EnJl4ZL5lwpaZWahd/Bx3iWNA9O2IQlHVlKeEoM3XxYQWyjg8CE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
